### ISSUE TITLE
Reddit PM

### ISSUE THREAD

**Issue by studerw** [enyfour5/chart_project#1]
Hey I sent you a PM on reddit with directions to connect to the server. There is one [other guy](https://github.com/preintercede) going to try a client too, so feel free to work together or 'borrow' ideas from each other, assuming you still want to work on this project.

**Comment by enyfour5** [comment]
Hey! I definitely still want to work on this project. I am on vacation and haven't really been looking at my e-mails/notifications. I will be back tomorrow night though. Thank you for reaching out! I will take a look at everything while i'm at the airport tomorrow night and get back to you with any questions that I might have.

**Comment by enyfour5** [comment]
hey, is this still going on?

**Comment by studerw** [comment]
If you are still interested, I have time this weekend as it’s a holiday in the US. Do you still want to do a front end project? How are your JS skills coming along?
